--- 
title: Replication of Ledoit and Wolf (2008, 2011, 2018) Functions
output: github_document
author: "Paulo Ferreira Naibert" 
bibliography: refs.bib
citation_package: natbib
includes:
in_header: preamble.tex
--- 

Original: 2019 October 13.

Current: `r format(Sys.time(), "%d, %B, %Y")`

## Overview
This Repository contains functions to replicate @lw2008, @lw2011, and @lw2018.

Michael Wolf provides `R` codes for those two papers on 
[his webpage](https://www.econ.uzh.ch/en/people/faculty/wolf.html), 
in the 
[publications section](https://www.econ.uzh.ch/en/people/faculty/wolf/publications.html).

What is found here is merely an edit of those codes.

If you find any bug, or technical error, please contact me.

## PAPERS and GOALS of the code
On @lw2008, @lw2011, and @lw2018, the authors provide methods to test the hypothesis of difference in the Sharpe Ratio and the Variance of two investment strategies.
The papers can be found in the following links:

[SR Paper](https://www.econ.uzh.ch/dam/jcr:ffffffff-935a-b0d6-0000-00007214c2bc/jef_2008pdf.pdf), 
[SR WP](http://www.econ.uzh.ch/static/wp_iew/iewwp320.pdf), 
[Variance Paper](https://www.econ.uzh.ch/dam/jcr:520edf26-2322-4708-8dde-51d61141914a/Ledoit_et_al-2011-Wilmott_Robust_Performance.pdf), 
[Variance WP](http://www.econ.uzh.ch/static/wp_iew/iewwp516.pdf),
[Generalized WP](http://www.econ.uzh.ch/static/wp/econwp305.pdf).

Also, I made a summary of those papers [here](vignette.pdf)

## Functions

The functions can be found [here](./R/LW-SR-VAR.R).
They are edits of the [`Sharpe.RData`](./R/Sharpe.RData) and [`Var.RData`](./R/Var.RData) files that can be found in Michael Wolf's website with some additions and modifications.

I didn't have enought time to modify the `block.size.calibrate()` functions.

## Data

For the data, I simpy saved the returns data of `Sharpe.RData` as a `.RDS` file.
Loading `rets.RDS` should result in a list object on the `R` Software [@R] .

## USAGE

See [DEMO](./DEMOS/) files.

# TODO
- Document Functions (R and html nb)

# DISCLAIMER

I own NONE of the rights to the codes.
I simply edited the already existing codes in
[Michael Wolf's Webpage](https://www.econ.uzh.ch/en/people/faculty/wolf.html).
I also offer NO support for the functions.
They are presented "AS IS".

# ACKNOWLEDGEMENTS
I would like to thank Michael Wolf for providing the original functions on his webstite.

# REFERENCES
